### ISSUE TITLE
18.04 CI tests failing

### ISSUE THREAD

**Issue by robert-ancell** [canonical/snapd-glib#168]
Node seems to be broken?
```
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

**Comment by sergio-costas** [comment]
Created a VM with 18.04, but nodejs works fine, at least installed with .deb... But the snap fails with a different error:

```
ubuntu@build-snapd-glib:~/basedir$ nodejs-binaries.node 
execv failed: No such file or directory
```

**Comment by sergio-costas** [comment]
Also tried replaying in my system all the docker commands, and everything worked as expected...

**Comment by sergio-costas** [comment]
Found the fix.
