### ISSUE TITLE
SnapdNotice getters return references

### ISSUE THREAD

**Issue by robert-ancell** [canonical/snapd-glib#170]
The getters in SnapdNotice return references (e.g. `snapd_notice_get_last_repeated`). This isn't necessary (the object is not created and is owned by the object) and doesn't match the style of the other objects (and GObject code in general). This is a risk on the API user who might forget to release the reference and requires more boilerplate code for simple cases.

It would be nice if we correct this, I see two options:
- Make new getters and deprecate the old ones, e.g. `snapd_notice_get_last_repeated2`. It's a little ugly but works.
- Make a new object SnapdNotice2 that has new methods. More work than the above and even more messy.

**Comment by robert-ancell** [comment]
@sergio-costas WDYT?

**Comment by robert-ancell** [comment]
Introduced in https://github.com/canonical/snapd-glib/pull/148

**Comment by sergio-costas** [comment]
In fact, I had the opposite case: I was freeing a pointer believing it was a reference. But if you consider that it should be done that way, I'm in.

Anyway, if we change that to pointers, as you suggest, should we add `const` to specify that it shouldn't be released?

**Comment by sergio-costas** [comment]
Mmm... you are right: the properties can only be set during construction, so they are constant.

**Comment by robert-ancell** [comment]
GObject code generally doesn't use const for this, so I think we shouldn't either for consistency (the existing code does not).
